name: Docs
on:
  push:
    branches:
      - master
    paths:
      - docs/**
      - lib/**
      - types/**
      - .github/workflows/docs.yml
      - browser.js
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install deps
        working-directory: docs
        run: npm install --no-progress --loglevel error
      - name: Build
        working-directory: docs
        run: make build
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/build
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v4
